version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 5432:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - tremos-network
   odoo:
        image: odoo:17.0
        restart: always
        ports:
                - 8069:8069
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/custom-addons
                - odoo-data:/var/lib/odoo
        networks:
                - tremos-network
volumes:
        odoo-data:
        db-data:
networks:
        tremos-network:
